### ISSUE TITLE
Homeassistant MQTT discovery shows climate is unavailable

### ISSUE THREAD

**Issue by Pr0mises** [anszom/rethink#1]
Hey @anszom firstly thank you for your amazing work in this.
I wanted to reverse it myself but somehow stumbled across your repo today, and It works!!

As I'm no node expert and didn't want to cluster my server up I wrote two dockerfiles, one for the client and one for the server, need to do some proper checks if it works out of the box. If you're interested, I can create a PR for that.

Now to my problem, everything works fine, the LG wall mounted AC connects to the server and publishes its topics towards it and I receive payloads inside HASS:
```
<ServerIP> LG Air Conditioner (climate.<redactedID>)
MQTT discovery data:

    Topic: homeassistant/climate/rethink/<redactedID>/config 

Payload:
availability:
  - topic: rethink/<redactedID>/availability
  - topic: rethink/availability
optimistic: false
object_id: <redactedID>
unique_id: <redactedID>
device:
  identifiers: <redactedID>
  manufacturer: LG
  model: RAC_056905_WW
  sw_version: '690409'
current_temperature_topic: rethink/<redactedID>/current_temperature
power_command_topic: rethink/<redactedID>/power/set
mode_state_topic: rethink/<redactedID>/mode
mode_command_topic: rethink/<redactedID>/mode/set
fan_mode_state_topic: rethink/<redactedID>/fan_mode
fan_mode_command_topic: rethink/<redactedID>/fan_mode/set
temperature_state_topic: rethink/<redactedID>/temperature
temperature_command_topic: rethink/<redactedID>/temperature/set
swing_mode_state_topic: rethink/<redactedID>/swing_mode
swing_mode_command_topic: rethink/<redactedID>/swing_mode/set
temperature_unit: C
temp_step: 0.5
precision: 0.5
fan_modes:
  - auto
  - very low
  - low
  - medium
  - high
  - very high
swing_modes:
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
  - 1-3
  - 3-5
  - 'on'
  - 'off'
vertical_swing_modes:
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
  - '6'
  - 'on'
  - 'off'
name: LG Air Conditioner
platform: mqtt
```
The subscribed topics are:
```
rethink/<redactedID>/availability
rethink/availability
rethink/<redactedID>/mode
rethink/<redactedID>/fan_mode
rethink/<redactedID>/swing_mode
rethink/<redactedID>/current_temperature
rethink/<redactedID>/temperature
```
So that's working as expected, but somehow the "LG Air Conditioner" climate entity shows "Unavailable".

I'm not sure if I missed something in the docs, debugging the MQTT component didn't help either, do you perhaps have a clue what could be wrong here?

Thank you in advance
